### ISSUE TITLE
Eloquent collection data available in initial render not available in livewire message nor JavaScript using livewire data property

### ISSUE THREAD

**Issue by ronald2wing** [livewire/volt#100]
### Volt Version

1.6.3

### Laravel Version

11.0.5

### PHP Version

8.3.3

### Description

Similar to https://github.com/livewire/livewire/issues/1641 but rules is defined for the Volt property.

The eloquent models are null in $wire even though the rules are defined.

### Steps To Reproduce

1. Create a public property in the volt component: state('musicVideo', fn () => MusicVideo::first())
2. Attempt to access the data by using $wire.musicVideo in the AlpineJS.

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
