### ISSUE TITLE
Make VS Code extension 

### ISSUE THREAD

**Issue by ZdenekKrcal** [livewire/volt#109]
Hello,

please make VS Code extension for Volt. There is no intellisence, formating etc.

Thank you.

**Comment by driesvints** [comment]
Thanks. We currently have no plans to do this ourselves but welcome community plugins.

**Comment by igoralentyev** [comment]
And how you assume we would use Volt without even basic autocomplete?

**Comment by inmanturbo** [comment]
> And how you assume we would use Volt without even basic autocomplete?

Actually even in vscode without any extension or plugin you can get language support by setting the interpreter to PHP. You can do so by clicking in the lower right where it says the current interpreter being used. If the way it does tokenization and syntax highlighting for the "blade" part of the file, you can just switch it back when editing your markup, to get your tailwind auto complete, etc. 

It may be a bit inconvenient to do so. Is it more inconvenient then jumping back and forth between a separate PHP file for your livewire class and a blade template, or less so?  Hard to say, and I guess it depends 🤷
