### ISSUE TITLE
Component paths are broken when using symlinks

### ISSUE THREAD

**Issue by inmanturbo** [livewire/volt#112]
### Volt Version

1.6

### Laravel Version

11.19.0

### PHP Version

8.2.21

### Description

When a package has a volt component and it (the package) is installed using composer's symlink option, the component paths loaded by the compiler are broken and sometimes contain double slashes, resulting in "Path cannot be empty error" when attempting to view a page containing the component.

Everything works fine when the package is installed normally and downloaded from a mirror, but this is not an ideal workflow for package development.

I've only attempted this on unix-like systems (linux and mac). Haven't tried Windows but that might matter, considering windows handles files paths and symlinks differently.

### Steps To Reproduce

Create a new laravel app, then start developing a package locally with a volt component, using composer's "symlink" option to install the package in your laravel project. Attempt to use the component in a page and view it using artisan serve, valet or herd.

**Comment by driesvints** [comment]
Thanks. Right now this isn't supported but you're welcome to send in a PR that we can have a look at.

**Comment by inmanturbo** [comment]
Just a note to self and anyone who may stumble across this:

This issue only seems to be encountered when using `../` in a relative path.

Using an absolute path and/or placing the (dev) package somewhere under the project root seems to fix this. E.G.:

### Doesn't Work

```json
    "repositories": [
        {
            "type": "path",
            "url": "../../packages/my-package",
            "options": {
                "symlink": true
            }
        }
    ]
```

### Works

```json
    "repositories": [
        {
            "type": "path",
            "url": "packages/*",
            "options": {
                "symlink": true
            }
        }
    ]
```

### Works

```json
    "repositories": [
        {
            "type": "path",
            "url": "/home/User/path/to/packages/my-package",
            "options": {
                "symlink": true
            }
        }
    ]
```
