### ISSUE TITLE
better error handling when routing to Volt components

### ISSUE THREAD

**Issue by cheekyboots** [livewire/volt#114]
When I route directly to Volt components using  Volt::route(), most errors in the view will throw a Symphony ViewException that says, "htmlspecialchars(): Argument #1 ($string) must be of type string, Closure given".

It's super unhelpful as an error. I have to use Telescope to figure out the actual problem. 

I've tried handling the error with a custom exception handler but have not been able to get it to work, probably because of it being a Symphony error.

**Comment by driesvints** [comment]
We'd very much appreciate any PR's that can help improve this 👍
