### ISSUE TITLE
Batch callbacks are not working when dispatched in a component.

### ISSUE THREAD

**Issue by KozSuper** [livewire/volt#115]
### Volt Version

1.6

### Laravel Version

11.9

### PHP Version

8.3

### Description

When creating a Batch with callbacks like progress, then, catch, finally, these callbacks are not working as expected. Everything works fine in the Controller.

### Steps To Reproduce

```php
new class extends Component {
    public function mount(){
      $jobs = //somejobs 
      $batch = Bus::batch([
        $jobs
      ])
      ->before(function (Batch $batch) {
          //working
      })->progress(function (Batch $batch) {
        // doesn't work
      })->then(function (Batch $batch) {
        // doesn't work
      })->catch(function (Batch $batch, Throwable $e) {
        // doesn't work
      })->finally(function (Batch $batch) {
        // doesn't work
      })->allowFailures()
      ->dispatch();
    }
}; ?>
```

**Comment by KozSuper** [comment]
![image](https://github.com/user-attachments/assets/233f8aad-4b6c-4ca9-b726-c9fa28d53d8c)

I think it's because of a serialization error. It can't be unserialized when dispatching in a Volt component.

**Comment by driesvints** [comment]
Think it's best you use a service class then for this one and use that in your Volt component. We'd always appreciate a PR to the docs if you discover an incompatibility.
