### ISSUE TITLE
Replace dots with slashes in `make:volt` command

### ISSUE THREAD

**Issue by azzazkhan** [livewire/volt#116]
Please update the `make:volt` component creation command to replace `.` with `/` as currently running the following command will create a component in `resources/views/livewire/dashboard.widget.blade.php` file but it's useless as we cannot use the period `.` delimiter in component names as like blade components it would make it search in sub-directory instead.

```bash
php artisan make:volt dashboard.widget
```

The above mentioned command should create a component file at `resources/views/livewire/dashboard/widget.blade.php`.

If this behavior is intended then please share a reference link or brief detail about such use case and scenario.

**Comment by driesvints** [comment]
I don't think we'll change this as this would be a breaking change.
