### ISSUE TITLE
States, Multiples Declarations

### ISSUE THREAD

**Issue by devajmeireles** [livewire/volt#13]
### Volt Version

v1.0.0@beta2

### Laravel Version

latest

### PHP Version

8.1.21

### Database Driver & Version

SQLite

### Description

I don't know if this is really a bug or expected behavior, **anyway I'm reporting this in order to help.**

1. State with closure and non-closure:

```php
<?php

use function Livewire\Volt\state;

state(['title' => fn () => $title], '');
```

👇 

![CleanShot 2023-08-01 at 1 08 15](https://github.com/livewire/volt/assets/60591772/80f1047b-011b-49d8-b84c-20738eec3c62)

2. State with closure and variable with no value:

```php
<?php

use function Livewire\Volt\state;

state(['title' => fn () => $title, 'description']);
```

👇 

![CleanShot 2023-08-01 at 1 09 29](https://github.com/livewire/volt/assets/60591772/76fdf509-53a0-4948-ac80-fd61198a53a9)

### Steps To Reproduce

Try to do the same thing as reported above.

**Comment by nunomaduro** [comment]
Both examples declare state incorrectly. Here are the ways you can declare state:

```php
state('counter');
state(['counter']);
state(['counter' => 0]);
state(counter: 0);
state(['counter' => fn () => User::count()]);
state(counter: fn () => User::count());
```
