### ISSUE TITLE
Call to undefined method Livewire\Volt\LivewireManager::styles()

### ISSUE THREAD

**Issue by philharmonie** [livewire/volt#14]
### Volt Version

v1.0.0-beta.2

### Laravel Version

10.17

### PHP Version

8.2.8

### Description

I get:
```
Call to undefined method Livewire\Volt\LivewireManager::styles()
```
for
```
@livewireStyles
```
Isn't it possible to use "old" livewire together with volt? Is it either one or the other?

### Steps To Reproduce

Installed Volt into an existing project, that already used livewire:
```
composer require livewire/livewire "^3.0@beta"
composer require livewire/volt "^1.0@beta"
```
Now I get:
```
Call to undefined method Livewire\Volt\LivewireManager::styles()
```
for
```
@livewireStyles
```

**Comment by nunomaduro** [comment]
I've just added a test that proves that both the directives `@livewireStyles` and `@livewireScripts` are working as expected. Can you update to the latest version of Laravel, Livewire, Folio and Volt, and re-open this issue if the issue persist? Thanks!
