### ISSUE TITLE
Laravel Echo Notifications

### ISSUE THREAD

**Issue by jdltechworks** [livewire/volt#30]
### Volt Version

1.0.0

### Laravel Version

10.10

### PHP Version

8.1

### Database Driver & Version

MySql 8.0 Sail

### Description

Is it possible to use echo notifications in the listeners?
Not sure what to do. All of these codes are not subscribing.

Thanks.

```
<?php

use function Livewire\Volt\{state, on};

on([
    'echo-private:App.Models.User.1,notification' => function () {
        
    },
]);

on([
    'echo-notification:App.Models.User.1,FriendRequestSent' => function () {
    },
]);

?>
```

### Steps To Reproduce

No detailed steps all is working on my end except for this.

**Comment by nunomaduro** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
