### ISSUE TITLE
Change layout for component-based Volt?

### ISSUE THREAD

**Issue by iambateman** [livewire/volt#32]
Is it possible to change the layout when using a full-page class-based Volt component?

### What I need
```php
new class extends Component {

      protected string $layout = 'components.layouts.guest';

}
```

### What I tried

I tried just including the function and following it with the class declaration, but it didn't work:
```php
layout('components.layouts.guest');

new class extends Component { ... }
``` 

P.S. Volt is *really* cool, thanks for all your collective work on it!

**Comment by nunomaduro** [comment]
You need to use Livewire attributes:

```php
new #[Layout('components.layouts.guest')]
class extends Component
{
    //
}; ?>
```

**Comment by iambateman** [comment]
That worked, thank you!

If someone else stumbles across this, the import for `Layout` is `use Livewire\Attributes\Layout;`
