### ISSUE TITLE
Issue with Bus facade/batches in computed property

### ISSUE THREAD

**Issue by undjike** [livewire/volt#47]
### Volt Version

1.3.0

### Laravel Version

10.10.0

### PHP Version

8.2.3

### Database Driver & Version

MySQL 8.0.28

### Description

I don't know what's wrong but this code generates an error.

```php
$batch = computed(fn () => Bus::findBatch($this->batchId));

// Even when I use a constant as batch ID like...
$batch = computed(fn () => Bus::findBatch('xxxxxxxx'));
```

![image](https://github.com/livewire/volt/assets/57102409/713e3320-a412-401a-bf3b-8041a5725f7c)
![image](https://github.com/livewire/volt/assets/57102409/a2044538-4ee1-47a6-a1a2-9f1ee43540b7)

Even if I create a variable to assign this expression on mount, same error.
But once I put something other than this expression, everything works.

I wonder whether it's caused by the Bus facade...

Here is how the view code looks like
![image](https://github.com/livewire/volt/assets/57102409/b9d8d23b-5c0a-4fcb-a830-6e723b02f077)

### Steps To Reproduce

In a Volt component (here anonymous), create a computed property retrieving a batch instance from the database.

**Comment by undjike** [comment]
Even this syntax causes the same issue.

![image](https://github.com/livewire/volt/assets/57102409/8f8d0b95-b4c1-4fef-9a35-ed3b531d0603)

Here, the `batchId` is coming from Folio.

**Comment by undjike** [comment]
More and more strange.

I even created a classic Livewire full page component.
But it seems like, with Volt installed, the problem stays the same.

![image](https://github.com/livewire/volt/assets/57102409/deb8ad13-3718-482a-a6ee-dfff167643f4)

**Comment by undjike** [comment]
I think I found out where this issue is coming from.

It's caused by these lines of code :

1. Within `\Illuminate\Bus\Dispatcher::findBatch`

![image](https://github.com/livewire/volt/assets/57102409/ba5e56d0-519e-42ad-bdbf-e62dd47f0487)

2. Within `\Illuminate\Bus\Batchable::batch`

![image](https://github.com/livewire/volt/assets/57102409/01521709-cc21-4757-b6e6-44da39be1e65)

Any idea of how we can tacle it?

**Comment by nunomaduro** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
