### ISSUE TITLE
Path cannot be empty error when creating anonymous volt component

### ISSUE THREAD

**Issue by hiddenLadder** [livewire/volt#5]
### Volt Version

1.0.0-beta.1

### Laravel Version

10.16.1

### PHP Version

8.2.1

### Database Driver & Version

MySQL 8.0.30

### Description

Getting error "Path cannot be empty" when i try to create an anonymous volt component inside folio page
![image](https://github.com/livewire/volt/assets/89526742/0aee661a-8319-4785-b9ba-e988ddbe37a0)
![image](https://github.com/livewire/volt/assets/89526742/9e4186e7-e9e3-4139-a33b-113fbd00107d)

### Steps To Reproduce

Install Laravel Folio, Livewire v3, Laravel Volt
Delete default route
Create a page with php artisan make:folio index
Add the following code 
```php
<?php

use function Livewire\Volt\{state};

state(['count' => 0]);
$increment = fn() => $this->count++;
?>
<div>
  index page
  @volt('counter')
    <div>
	    <p>{{$count}}</p>
	    <button wire:click="increment">+</button>
    </div>
  @endvolt
</div>
```
Try to load the folio route with the browser

**Comment by nunomaduro** [comment]
@hiddenLadder You using windows right?

**Comment by hiddenLadder** [comment]
Yes, tried to set upload_tmp_dir in php.ini but didnt help
