### ISSUE TITLE
The `assertSessionHas()` does not work with flash messages.

### ISSUE THREAD

**Issue by robsontenorio** [livewire/volt#54]
### Volt Version

1.3.2

### Laravel Version

10.23

### PHP Version

8.2

### Description

The `assertSessionHas()` does not work with flash messages.

## Volt component
```php
<?php

use Livewire\Volt\Component;

new class extends Component
{
    public function save()
    {
        session()->flash('message', 'ops!');
    }
}; ?>

<div>
    volt abc
</div>
```

### Test

```php
Volt::test('mycomponent')
            ->call('save')
            ->assertSessionHas('message', 'ops!');
```

### Fail

<img width="458" alt="image" src="https://github.com/livewire/volt/assets/118955/08edc5a3-3d7e-4bdd-821a-d860f6955f52">

**Comment by inmanturbo** [comment]
does is work for you with other session data? or is it only flash data?

**Comment by robsontenorio** [comment]
@inmanturbo 

flash() does not work. 
session([x => y]) works. 

But the use case issue is about test flash() message.

**Comment by robsontenorio** [comment]
Ok, guys … just got it. 

There is not any kind of “redirect” so flash message is not “trigged”.

**Comment by nunomaduro** [comment]
Can you double check if this issue also happens when using regular Livewire components? If not, please re-open this issue.

**Comment by jhjvandenbroek** [comment]
I can confirm the issue also occurs in a normal Livewire component
