### ISSUE TITLE
Volt component syntax for plain anonymous Blade components 

### ISSUE THREAD

**Issue by Wulfheart** [livewire/volt#56]
Hello,

I really like Laravel Volt and its way to declare components and markup directly together. What I am missing now is a way to also apply this syntax to plain Blade components. It would be nice to also have this option. 

After some consideration I think this should also live in this package as it is responsible for the “new” way to declare components. 
So my idea would be to add it to anonymous components. If you are generally interested I can 
1. write a RFC-like proposal so that the idea can be evaluated further if requested 
2. also contribute this feature

Thank you in advance for your consideration.

**Comment by nunomaduro** [comment]
Write this message here: https://github.com/laravel/framework/discussions. To see what people think.
