### ISSUE TITLE
Livewire Volt::actingAs() method

### ISSUE THREAD

**Issue by nmfirdausw** [livewire/volt#60]
I was writing test using PEST2,
Since I was using Volt and need to write test for function that have auth()->user(),
It was return null since no actingAs method to use in Volt Class.

Hope It would be better if Volt also have this function below.

```
Livewire::actingAs($user)
->test(UpdatePost::class, ['post' => $post])
->set('title', 'Living the lavender life')
->call('save')
->assertUnauthorized();
```

**Comment by driesvints** [comment]
Feel free to attempt a PR 👍

**Comment by nunomaduro** [comment]
This is fixed. Ships next week.

**Comment by nmfirdausw** [comment]
Thanks @nunomaduro
