### ISSUE TITLE
Can't use closures for validation

### ISSUE THREAD

**Issue by GithubEficienciaTributaria** [livewire/volt#66]
### Volt Version

1.4

### Laravel Version

10.31.0

### PHP Version

8.2

### Database Driver & Version

mariadb 10.4.31

### Description

When trying to setup dynamic validation for my component, I used a closure inside the rules function, but when I try to access the page with my component, I get the following error:  array_merge(): Argument #2 must be of type array, Closure given.

### Steps To Reproduce

1. Create a livewire volt component
2. Create a validation with a closure like, rules(fn () => [ 'name' => ['required'] ]);
3. Reload the page.

![error](https://github.com/livewire/volt/assets/133399447/f4f2a10d-9857-4bc8-bf86-2c61787bd2d8)

**Comment by RVxLab** [comment]
I saw this happen on 1.3.x as well. Let me see if I can make a PR for this.

**Comment by RVxLab** [comment]
Made a PR for this and got it working locally.

**Comment by driesvints** [comment]
Thanks all. Let's see how the PR goes.
