### ISSUE TITLE
Problem with namespace

### ISSUE THREAD

**Issue by hamzaelmaghari** [livewire/volt#68]
### Volt Version

Latest

### Laravel Version

10

### PHP Version

8.2

### Database Driver & Version

MySQL

### Description

There is a problem with. the namespace, when calling artisan command `VOLT::INSTALL` it automaticaly creates views folder called `livewire` but, what if in my livewire config I have modified it?

Thanks to make custom volt config file.

### Steps To Reproduce

Install the package manually and change livewire's view namespace.

**Comment by driesvints** [comment]
Thanks. Can you resend your PR with passing tests?
