### ISSUE TITLE
Artisan command volt file generator not creating folders.

### ISSUE THREAD

**Issue by joydeep-bhowmik** [livewire/volt#83]
### Volt Version

1.6

### Laravel Version

10.10

### PHP Version

8.2.4

### Description

```cmd
php artisan make:volt folder.counter
```
generated `livewire\folder.counter.blade.php` instead of creating `livewire\folder\counter.php`

### Steps To Reproduce

run this command after installing livewire-volt 
`php artisan make:volt folder.counter`

**Comment by nunomaduro** [comment]
We don't support the (dot) syntax in this command. Please use a directory separator instead: 

```
php artisan make:volt folder/counter
```

**Comment by joydeep-bhowmik** [comment]
> We don't support the (dot) syntax in this command. Please use a directory separator instead:
> 
> ```
> php artisan make:volt folder/counter
> ```

So in future laravel we will use directory separator instead to dot separator?
