### ISSUE TITLE
Calling Volt::mount a second time negates initial call

### ISSUE THREAD

**Issue by inmanturbo** [livewire/volt#87]
### Volt Version

1.3

### Laravel Version

10.31.0

### PHP Version

8.3.1

### Description

Calling `Volt::mount()` more than once overwrites the first call. This makes it impossible for packages to use `Volt::mount()` to register their own components.

### Steps To Reproduce

```php

<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Livewire\Volt\Volt;

class VoltServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        Volt::mount([
            config('livewire.view_path', resource_path('views/livewire')),
            resource_path('views/pages'),
        ]);

        Volt::mount([
            resource_path('views/vendor/demo/livewire'),
        ]);
    }
}
```

Install volt. Add code above to Volt service provider. Run `php artisan make:volt counter`. Use counter component in view. 

Run the command below to copy the component to a new component called `vendor-counter` in the "vendor/demo" path set up in our provider.

 ```bash
mkdir -p resources/views/vendor/demo/livewire \
  && cp resources/views/livewire/counter.blade.php \
  resources/views/vendor/demo/livewire/vendor-counter.blade.php 
```

Attempt to use both in a view:

```blade
  @livewire('counter')
  @livewire('vendor-counter')
```

See error:

```
InvalidArgumentException
PHP 8.3.1
10.41.0
View [counter] not found.

counter was not found.
Are you sure the view exists and is a .blade.php file?
```

example repo: https://github.com/inmanturbo/volt-bug-report

**Comment by driesvints** [comment]
Thanks. Please provide thorough steps to reproduce this with code examples.

**Comment by inmanturbo** [comment]
@driesvints Thank you for reviewing the issue. I've updated the steps with more complete examples, and included a link to an [example-repo](https://github.com/inmanturbo/volt-bug-report).

**Comment by inmanturbo** [comment]
Here is an example workaround I've used:

```php
trait MergesVoltMounts
{
    protected function mergeVoltMounts($paths)
    {
        $voltPaths = collect(Volt::paths())->map(function ($path) {
            return $path->path;
        })->toArray();

        $paths = array_merge($voltPaths, $paths);

        Volt::mount($paths);
    }
}
```

https://github.com/inmanturbo/b2bsaas/blob/64984d4a42710b98e8441aab10ffca7db87e36a9/inmanturbo/b2bsaas/src/MergesVoltMounts.php

**Comment by driesvints** [comment]
Hi @inmanturbo. Thanks for the good example. This indeed doesn't seem possible. One solution packages can take for now is to ask app developers to add the paths to the `Volt::mount` call in their service provider. Or you can attempt a PR so path's get added additionally with the mount call.

**Comment by robsontenorio** [comment]
@inmanturbo 

Your "Trait" workaround is not available anymore.

I have tried to use your snippet  on `MyPackageServiceProvider@boot()` method. But, it does not work, because we can guarantee the order. The `Volt::paths()` is empty at this moment.

**Comment by robsontenorio** [comment]
This worked. Is it reliable ?

@driesvints  @inmanturbo 

```php
 public function register()
    {
       ....

        $this->app->booted(function () {
            Volt::mount([.. bypath..]);
        });

       ....
    }
```

**Comment by inmanturbo** [comment]
@robsontenorio to a certain extent it is. If somehow there's a later call to `volt::mount()` that doesn't include or merge in the existing mounts it will be lost, but that can't be helped.

**Comment by robsontenorio** [comment]
@inmanturbo Do you have a better definitive salutation?

**Comment by inmanturbo** [comment]
Short of a PR or something like #88, no. Aside from writing an install command for the components, or simply using vanilla Livewire.

**Comment by bookwyrm** [comment]
@robsontenorio and @inmanturbo I opened #95 which provides the same behavior as #88 but with a simpler solution.

**Comment by robsontenorio** [comment]
Thanks @bookwyrm 🙏

**Comment by inmanturbo** [comment]
@robsontenorio yeah much simpler. Thanks!

**Comment by inmanturbo** [comment]
@bookwyrm yeah much simpler. Thank you!
