### ISSUE TITLE
In volt class mode, line mismatch occurs when debugging breakpoints with xdebug in PhpStorm

### ISSUE THREAD

**Issue by xiaoxidashen** [livewire/volt#90]
### Volt Version

1.6.1

### Laravel Version

10.43.0

### PHP Version

 8.2.9

### Database Driver & Version

sqlite

### Description

In volt class mode, line mismatch occurs when debugging breakpoints with xdebug in PhpStorm. I have no choice but to use the non-volt mode

### Steps To Reproduce

see description

**Comment by xiaoxidashen** [comment]
The blade debugging option is checked

**Comment by driesvints** [comment]
I don't think this is supported right now sorry. But we'd happily accept PR's to make this possible.
