### ISSUE TITLE
[Docs]: Develop Livewire package with Volt

### ISSUE THREAD

**Issue by robsontenorio** [livewire/volt#92]
Currently there is no direction about how to develop a package using Volt component. Is it possible?

Using regular Livewire component it works. 

<livewire:some-component />

<img width="780" alt="image" src="https://github.com/livewire/volt/assets/118955/4cd5f993-a6d2-41b6-823e-1fa2ed848b46">

And about Volt?

**Comment by inmanturbo** [comment]
It won't work. You have to call volt::mount from your service provider to mount your package's livewire directory.

You will have to wrap it inside $this->app-> booted() or something like that to get it to happen after volt is mounted inside the main app, and merge in the existing mount paths. Something like this:

```php
$voltPaths = collect(Volt::paths())->map(function ($path) {
            return $path->path;
        })->toArray();

$paths = array_merge($voltPaths, __DIR__. '/../../resources/views/livewire');

Volt::mount($paths);
```

Sorry for any typos. On my phone.

**Comment by inmanturbo** [comment]
See https://github.com/livewire/volt/issues/87

**Comment by inmanturbo** [comment]
Alternatively, you could direct those who use the package to add your package's directory paths to the call to volt::mount() in their volt service provider.

**Comment by driesvints** [comment]
Thanks @inmanturbo
