### ISSUE TITLE
Support for Volt components in non-default locations

### ISSUE THREAD

**Issue by bookwyrm** [livewire/volt#94]
I'm working on a private, custom package and I'd like to be able to ship a Volt component in the package.

I can use `Livewire\Volt\MountedDirectories->mount()` to add my local `views/livewire` directory but since `mount()` uses `View::replaceNamespace()` there is no persistent way to tell Volt about my views directory.

Can the code use `View::addNamespace()` instead or provide some other means of adding additional directories to be used when looking for a Volt view file?

**Comment by bookwyrm** [comment]
I think that a switch from `replaceNamespace` to `addNameSpace` would address #87

**Comment by bookwyrm** [comment]
After looking at the code more, I think that #95 is a better solution

**Comment by driesvints** [comment]
Looks like you already sent in a PR so let's see how that goes. Thanks
