### ISSUE TITLE
Volt documented  example showing error

### ISSUE THREAD

**Issue by joydeep-bhowmik** [livewire/volt#99]
### Volt Version

1.6.2

### Laravel Version

10.10

### PHP Version

8.2.12

### Description

```php
<?php
 
use function Livewire\Volt\{state};
 
state('count');
 
$increment = function () {
    // Store the new count value in the database...
 
    $this->count++;
};
 
?>
 
<x-app-layout>
    <x-slot name="header">
        Initial value: {{ $count }}
    </x-slot>
 
    @volt('counter')
        <div>
            <h1>{{ $count }}</h1>
            <button wire:click="increment">+</button>
        </div>
    @endvolt
</x-app-layout>

```

[This example ](https://livewire.laravel.com/docs/volt#passing-data-to-anonymous-components) returns Undefined variable $count for ` Initial value: {{ $count }}` 

### Steps To Reproduce

just install volt 1.6.2 and use the mentioned example

**Comment by driesvints** [comment]
Just works for me.

**Comment by joydeep-bhowmik** [comment]
> Just works for me.

any possible reason it's not working for me? 
I did clear the compiled views 
My livewire version: 3.4
My volt version:1.6.2

I installed volt with breeze

**Comment by kemalozvarol2** [comment]
Same error happening with me too. Have you found a solution?

Versions : 
livewire/livewire : ^3.5 (v3.5.9)
livewire/volt : ^1.6 (v1.6.5)
laravel/framework : ^11.9(v11.26.0)

**Comment by joydeep-bhowmik** [comment]
> Same error happening with me too. Have you found a solution?
> 
> Versions : livewire/livewire : ^3.5 (v3.5.9) livewire/volt : ^1.6 (v1.6.5) laravel/framework : ^11.9(v11.26.0)

nope still no solution to this ... livewire variables are only available within volt directives

**Comment by philharmonie** [comment]
> > nope still no solution to this ... seems like livewire variables are only available within volt directives
> 
> Mine was solved when I called the component from a blade file. I was returning the component directly from a route like;
> 
> ```
> Route::view('counter', 'livewire.counter');
> ```
> 
> I changed it to
> 
> ```
> Route::view('welcome');
> ```
> 
> And in the `welcome.blade.php` I put :
> 
> ```
> <livewire:counter />
> ```
> 
> Were you also trying to return the component from the route file?

That's the solution to the issue. But to solve the issue, alternatively a [full page component render ](https://livewire.laravel.com/docs/volt#full-page-components)would work as well:

```php
use Livewire\Volt\Volt;
 
Volt::route('/counter', 'livewire.counter');
```

**Comment by sToiBe** [comment]
I had the same issue. I solved it with this line: `<livewire:(insert here your volt) /> OR @livewire('products')`

In my case, I was importing this code from my dashboard: `@include('livewire.Products')`

I hope that helps you. Good code!
